# Generated by Django 5.2 on 2025-05-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0004_tag_task_tags'),
        ('users', '0002_remove_profile_avatar_remove_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(to='userProfile.tag'),
        ),
    ]
