# Generated by Django 5.2 on 2025-04-15 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
    ]
