# Generated by Django 5.2 on 2025-05-11 09:54

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('isCompleted', models.BooleanField(default=False)),
                ('isExpired', models.BooleanField(default=False)),
                ('wasCompletedBefore', models.BooleanField(default=False)),
                ('dateTime_due', models.DateTimeField(default=datetime.date.today)),
                ('xp', models.IntegerField(default=0)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userProfile.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remind_before_days', models.PositiveIntegerField(default=1, help_text='За сколько дней напоминать')),
                ('repeat_interval', models.PositiveIntegerField(default=0, help_text='Интервал повторения напоминаний (в днях), 0 - не повторять')),
                ('reminder_time', models.TimeField(default='09:00')),
                ('last_reminder_sent', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder', to='userProfile.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='taskType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userProfile.tasktype'),
        ),
    ]
