# Generated by Django 5.2 on 2025-05-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='wasCompletedBefore',
            field=models.BooleanField(default=False),
        ),
    ]
