# Generated by Django 5.2 on 2025-05-11 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='dateTime_due',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 11, 10, 44, 33, 297634, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
