# Generated by Django 5.2 on 2025-05-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_task_wascompletedbefore'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='isExpired',
            field=models.BooleanField(default=False),
        ),
    ]
