# Generated by Django 5.2 on 2025-05-11 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_alter_subject_name_alter_task_datetime_due_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dateTime_due',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 11, 12, 16, 15, 306471, tzinfo=datetime.timezone.utc)),
        ),
    ]
