# Generated by Django 5.2 on 2025-05-11 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_alter_task_datetime_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, 'priority 1'), (2, 'priority 2'), (3, 'priority 3'), (4, 'priority 4')], default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='dateTime_due',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 11, 14, 34, 50, 781147, tzinfo=datetime.timezone.utc)),
        ),
    ]
