# Generated by Django 5.2 on 2025-04-15 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_due',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
