# Generated by Django 5.2 on 2025-04-17 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0004_task_date_due'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date_due',
        ),
        migrations.AddField(
            model_name='task',
            name='dateTime_due',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
