# Generated by Django 5.2 on 2025-05-11 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0004_task_priority_alter_task_datetime_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dateTime_due',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 11, 14, 46, 56, 750381, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=4),
        ),
    ]
