# Generated by Django 5.2 on 2025-05-12 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0005_alter_task_datetime_due_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dateTime_due',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 12, 9, 30, 31, 223778, tzinfo=datetime.timezone.utc)),
        ),
    ]
