# Generated by Django 5.2 on 2025-04-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0005_remove_task_date_due_task_datetime_due'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tag',
        ),
        migrations.AddField(
            model_name='task',
            name='subject',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='taskType',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
