# Generated by Django 5.2 on 2025-05-12 14:44

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0006_alter_task_datetime_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='dateTime_due',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 12, 14, 44, 5, 188814, tzinfo=datetime.timezone.utc)),
        ),
    ]
