# Generated by Django 5.2 on 2025-04-22 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0006_remove_task_tag_task_subject_task_tasktype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
    ]
