# Generated by Django 5.2 on 2025-04-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0007_remove_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='xp',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
