# Generated by Django 5.2 on 2025-04-29 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0008_task_xp_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remind_before_days', models.PositiveIntegerField(default=1, help_text='За сколько дней напоминать')),
                ('repeat_interval', models.PositiveIntegerField(default=0, help_text='Интервал повторения напоминаний (в днях), 0 - не повторять')),
                ('last_reminder_sent', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder', to='userProfile.task')),
            ],
        ),
    ]
