# Generated by Django 5.2 on 2025-04-30 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0009_taskreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskreminder',
            name='reminder_time',
            field=models.TimeField(default='09:00'),
        ),
    ]
